[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
connect_four = "Hz8NQzqdznZBHQJKijt2XQi77E2PfqwNcmAwGn3bF7kY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/afofa/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
